language: node_js
node_js:
  - stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn global add codecov
  - yarn

script:
  - yarn run flow && yarn run lint && yarn run test --runInBand
  - codecov
